export const MUTATION_LOGIN = 'LOGIN_MUTATION_KEY';
export const MUTATION_REGISTER = 'REGISTER_MUTATION_KEY';
export const QUERY_ORDERS = 'ORDERS_QUERY_KEY';
export const MUTATION_CREATE_ORDER = 'CREATE_ORDER_MUTATION_KEY';
export const MUTATION_DELETE_ORDER = 'DELETE_ORDER_MUTATION_KEY';
